/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as CardSlugRouteImport } from './routes/card.$slug'
import { Route as ApiMpImageRouteImport } from './routes/api/mp-image'
import { Route as ApiMpAttachmentRouteImport } from './routes/api/mp-attachment'
import { Route as ApiMarketplaceFeedbackRouteImport } from './routes/api/marketplace-feedback'
import { Route as ApiGeocodeDirectoryQueryRouteImport } from './routes/api/geocode-directory-query'
import { Route as ApiGeocodeBrandingRouteImport } from './routes/api/geocode-branding'
import { Route as ApiGeocodeBeaconRouteImport } from './routes/api/geocode-beacon'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedAgentDashboardRouteImport } from './routes/_authenticated.agent-dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as PSlugIndexRouteImport } from './routes/p.$slug.index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated.dashboard.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as WorkOrdersRateTokenRouteImport } from './routes/work-orders.rate.$token'
import { Route as PSlugDemoRouteImport } from './routes/p.$slug.demo'
import { Route as PSlugBuilderRouteImport } from './routes/p.$slug.builder'
import { Route as MarketplaceFeedbackTokenRouteImport } from './routes/marketplace.feedback.$token'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AgentsMatchMatchTokenRouteImport } from './routes/agents.match.$matchToken'
import { Route as AuthenticatedDashboardWorkOrdersRouteImport } from './routes/_authenticated.dashboard.work-orders'
import { Route as AuthenticatedDashboardVaultRouteImport } from './routes/_authenticated.dashboard.vault'
import { Route as AuthenticatedDashboardUpgradeRouteImport } from './routes/_authenticated.dashboard.upgrade'
import { Route as AuthenticatedDashboardStatsRouteImport } from './routes/_authenticated.dashboard.stats'
import { Route as AuthenticatedDashboardPricingRouteImport } from './routes/_authenticated.dashboard.pricing'
import { Route as AuthenticatedDashboardPayoutsRouteImport } from './routes/_authenticated.dashboard.payouts'
import { Route as AuthenticatedDashboardOrdersRouteImport } from './routes/_authenticated.dashboard.orders'
import { Route as AuthenticatedDashboardMarketplaceRouteImport } from './routes/_authenticated.dashboard.marketplace'
import { Route as AuthenticatedDashboardDemoRouteImport } from './routes/_authenticated.dashboard.demo'
import { Route as AuthenticatedDashboardClientsRouteImport } from './routes/_authenticated.dashboard.clients'
import { Route as AuthenticatedDashboardBrandingRouteImport } from './routes/_authenticated.dashboard.branding'
import { Route as AuthenticatedDashboardAccountRouteImport } from './routes/_authenticated.dashboard.account'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated.admin.settings'
import { Route as AuthenticatedAdminServiceMatchesRouteImport } from './routes/_authenticated.admin.service-matches'
import { Route as AuthenticatedAdminProviderIdRouteImport } from './routes/_authenticated.admin.$providerId'
import { Route as AuthenticatedAgentDashboardWorkOrdersIndexRouteImport } from './routes/_authenticated.agent-dashboard.work-orders.index'
import { Route as AuthenticatedAdminServiceMatchesIndexRouteImport } from './routes/_authenticated.admin.service-matches.index'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as AuthenticatedDashboardVaultTemplatesRouteImport } from './routes/_authenticated.dashboard.vault.templates'
import { Route as AuthenticatedAgentDashboardWorkOrdersIdRouteImport } from './routes/_authenticated.agent-dashboard.work-orders.$id'
import { Route as AuthenticatedAdminServiceMatchesMatchTokenRouteImport } from './routes/_authenticated.admin.service-matches.$matchToken'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CardSlugRoute = CardSlugRouteImport.update({
  id: '/card/$slug',
  path: '/card/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMpImageRoute = ApiMpImageRouteImport.update({
  id: '/api/mp-image',
  path: '/api/mp-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMpAttachmentRoute = ApiMpAttachmentRouteImport.update({
  id: '/api/mp-attachment',
  path: '/api/mp-attachment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketplaceFeedbackRoute = ApiMarketplaceFeedbackRouteImport.update({
  id: '/api/marketplace-feedback',
  path: '/api/marketplace-feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeocodeDirectoryQueryRoute =
  ApiGeocodeDirectoryQueryRouteImport.update({
    id: '/api/geocode-directory-query',
    path: '/api/geocode-directory-query',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGeocodeBrandingRoute = ApiGeocodeBrandingRouteImport.update({
  id: '/api/geocode-branding',
  path: '/api/geocode-branding',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeocodeBeaconRoute = ApiGeocodeBeaconRouteImport.update({
  id: '/api/geocode-beacon',
  path: '/api/geocode-beacon',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgentDashboardRoute =
  AuthenticatedAgentDashboardRouteImport.update({
    id: '/agent-dashboard',
    path: '/agent-dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PSlugIndexRoute = PSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PSlugRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const WorkOrdersRateTokenRoute = WorkOrdersRateTokenRouteImport.update({
  id: '/work-orders/rate/$token',
  path: '/work-orders/rate/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugDemoRoute = PSlugDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => PSlugRoute,
} as any)
const PSlugBuilderRoute = PSlugBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => PSlugRoute,
} as any)
const MarketplaceFeedbackTokenRoute =
  MarketplaceFeedbackTokenRouteImport.update({
    id: '/marketplace/feedback/$token',
    path: '/marketplace/feedback/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsMatchMatchTokenRoute = AgentsMatchMatchTokenRouteImport.update({
  id: '/match/$matchToken',
  path: '/match/$matchToken',
  getParentRoute: () => AgentsRoute,
} as any)
const AuthenticatedDashboardWorkOrdersRoute =
  AuthenticatedDashboardWorkOrdersRouteImport.update({
    id: '/work-orders',
    path: '/work-orders',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardVaultRoute =
  AuthenticatedDashboardVaultRouteImport.update({
    id: '/vault',
    path: '/vault',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardUpgradeRoute =
  AuthenticatedDashboardUpgradeRouteImport.update({
    id: '/upgrade',
    path: '/upgrade',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardStatsRoute =
  AuthenticatedDashboardStatsRouteImport.update({
    id: '/stats',
    path: '/stats',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPricingRoute =
  AuthenticatedDashboardPricingRouteImport.update({
    id: '/pricing',
    path: '/pricing',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPayoutsRoute =
  AuthenticatedDashboardPayoutsRouteImport.update({
    id: '/payouts',
    path: '/payouts',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardOrdersRoute =
  AuthenticatedDashboardOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMarketplaceRoute =
  AuthenticatedDashboardMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardDemoRoute =
  AuthenticatedDashboardDemoRouteImport.update({
    id: '/demo',
    path: '/demo',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardClientsRoute =
  AuthenticatedDashboardClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBrandingRoute =
  AuthenticatedDashboardBrandingRouteImport.update({
    id: '/branding',
    path: '/branding',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAccountRoute =
  AuthenticatedDashboardAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminServiceMatchesRoute =
  AuthenticatedAdminServiceMatchesRouteImport.update({
    id: '/service-matches',
    path: '/service-matches',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProviderIdRoute =
  AuthenticatedAdminProviderIdRouteImport.update({
    id: '/$providerId',
    path: '/$providerId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAgentDashboardWorkOrdersIndexRoute =
  AuthenticatedAgentDashboardWorkOrdersIndexRouteImport.update({
    id: '/work-orders/',
    path: '/work-orders/',
    getParentRoute: () => AuthenticatedAgentDashboardRoute,
  } as any)
const AuthenticatedAdminServiceMatchesIndexRoute =
  AuthenticatedAdminServiceMatchesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminServiceMatchesRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardVaultTemplatesRoute =
  AuthenticatedDashboardVaultTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedDashboardVaultRoute,
  } as any)
const AuthenticatedAgentDashboardWorkOrdersIdRoute =
  AuthenticatedAgentDashboardWorkOrdersIdRouteImport.update({
    id: '/work-orders/$id',
    path: '/work-orders/$id',
    getParentRoute: () => AuthenticatedAgentDashboardRoute,
  } as any)
const AuthenticatedAdminServiceMatchesMatchTokenRoute =
  AuthenticatedAdminServiceMatchesMatchTokenRouteImport.update({
    id: '/$matchToken',
    path: '/$matchToken',
    getParentRoute: () => AuthenticatedAdminServiceMatchesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/opportunities': typeof OpportunitiesRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/agent-dashboard': typeof AuthenticatedAgentDashboardRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/api/geocode-beacon': typeof ApiGeocodeBeaconRoute
  '/api/geocode-branding': typeof ApiGeocodeBrandingRoute
  '/api/geocode-directory-query': typeof ApiGeocodeDirectoryQueryRoute
  '/api/marketplace-feedback': typeof ApiMarketplaceFeedbackRoute
  '/api/mp-attachment': typeof ApiMpAttachmentRoute
  '/api/mp-image': typeof ApiMpImageRoute
  '/card/$slug': typeof CardSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/invite/$token': typeof InviteTokenRoute
  '/p/$slug': typeof PSlugRouteWithChildren
  '/admin/$providerId': typeof AuthenticatedAdminProviderIdRoute
  '/admin/service-matches': typeof AuthenticatedAdminServiceMatchesRouteWithChildren
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/dashboard/account': typeof AuthenticatedDashboardAccountRoute
  '/dashboard/branding': typeof AuthenticatedDashboardBrandingRoute
  '/dashboard/clients': typeof AuthenticatedDashboardClientsRoute
  '/dashboard/demo': typeof AuthenticatedDashboardDemoRoute
  '/dashboard/marketplace': typeof AuthenticatedDashboardMarketplaceRoute
  '/dashboard/orders': typeof AuthenticatedDashboardOrdersRoute
  '/dashboard/payouts': typeof AuthenticatedDashboardPayoutsRoute
  '/dashboard/pricing': typeof AuthenticatedDashboardPricingRoute
  '/dashboard/stats': typeof AuthenticatedDashboardStatsRoute
  '/dashboard/upgrade': typeof AuthenticatedDashboardUpgradeRoute
  '/dashboard/vault': typeof AuthenticatedDashboardVaultRouteWithChildren
  '/dashboard/work-orders': typeof AuthenticatedDashboardWorkOrdersRoute
  '/agents/match/$matchToken': typeof AgentsMatchMatchTokenRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/marketplace/feedback/$token': typeof MarketplaceFeedbackTokenRoute
  '/p/$slug/builder': typeof PSlugBuilderRoute
  '/p/$slug/demo': typeof PSlugDemoRoute
  '/work-orders/rate/$token': typeof WorkOrdersRateTokenRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/p/$slug/': typeof PSlugIndexRoute
  '/admin/service-matches/$matchToken': typeof AuthenticatedAdminServiceMatchesMatchTokenRoute
  '/agent-dashboard/work-orders/$id': typeof AuthenticatedAgentDashboardWorkOrdersIdRoute
  '/dashboard/vault/templates': typeof AuthenticatedDashboardVaultTemplatesRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/admin/service-matches/': typeof AuthenticatedAdminServiceMatchesIndexRoute
  '/agent-dashboard/work-orders/': typeof AuthenticatedAgentDashboardWorkOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/opportunities': typeof OpportunitiesRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/agent-dashboard': typeof AuthenticatedAgentDashboardRouteWithChildren
  '/api/geocode-beacon': typeof ApiGeocodeBeaconRoute
  '/api/geocode-branding': typeof ApiGeocodeBrandingRoute
  '/api/geocode-directory-query': typeof ApiGeocodeDirectoryQueryRoute
  '/api/marketplace-feedback': typeof ApiMarketplaceFeedbackRoute
  '/api/mp-attachment': typeof ApiMpAttachmentRoute
  '/api/mp-image': typeof ApiMpImageRoute
  '/card/$slug': typeof CardSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/invite/$token': typeof InviteTokenRoute
  '/admin/$providerId': typeof AuthenticatedAdminProviderIdRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/dashboard/account': typeof AuthenticatedDashboardAccountRoute
  '/dashboard/branding': typeof AuthenticatedDashboardBrandingRoute
  '/dashboard/clients': typeof AuthenticatedDashboardClientsRoute
  '/dashboard/demo': typeof AuthenticatedDashboardDemoRoute
  '/dashboard/marketplace': typeof AuthenticatedDashboardMarketplaceRoute
  '/dashboard/orders': typeof AuthenticatedDashboardOrdersRoute
  '/dashboard/payouts': typeof AuthenticatedDashboardPayoutsRoute
  '/dashboard/pricing': typeof AuthenticatedDashboardPricingRoute
  '/dashboard/stats': typeof AuthenticatedDashboardStatsRoute
  '/dashboard/upgrade': typeof AuthenticatedDashboardUpgradeRoute
  '/dashboard/vault': typeof AuthenticatedDashboardVaultRouteWithChildren
  '/dashboard/work-orders': typeof AuthenticatedDashboardWorkOrdersRoute
  '/agents/match/$matchToken': typeof AgentsMatchMatchTokenRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/marketplace/feedback/$token': typeof MarketplaceFeedbackTokenRoute
  '/p/$slug/builder': typeof PSlugBuilderRoute
  '/p/$slug/demo': typeof PSlugDemoRoute
  '/work-orders/rate/$token': typeof WorkOrdersRateTokenRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/p/$slug': typeof PSlugIndexRoute
  '/admin/service-matches/$matchToken': typeof AuthenticatedAdminServiceMatchesMatchTokenRoute
  '/agent-dashboard/work-orders/$id': typeof AuthenticatedAgentDashboardWorkOrdersIdRoute
  '/dashboard/vault/templates': typeof AuthenticatedDashboardVaultTemplatesRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/admin/service-matches': typeof AuthenticatedAdminServiceMatchesIndexRoute
  '/agent-dashboard/work-orders': typeof AuthenticatedAgentDashboardWorkOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/agents': typeof AgentsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/opportunities': typeof OpportunitiesRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/agent-dashboard': typeof AuthenticatedAgentDashboardRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/api/geocode-beacon': typeof ApiGeocodeBeaconRoute
  '/api/geocode-branding': typeof ApiGeocodeBrandingRoute
  '/api/geocode-directory-query': typeof ApiGeocodeDirectoryQueryRoute
  '/api/marketplace-feedback': typeof ApiMarketplaceFeedbackRoute
  '/api/mp-attachment': typeof ApiMpAttachmentRoute
  '/api/mp-image': typeof ApiMpImageRoute
  '/card/$slug': typeof CardSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/invite/$token': typeof InviteTokenRoute
  '/p/$slug': typeof PSlugRouteWithChildren
  '/_authenticated/admin/$providerId': typeof AuthenticatedAdminProviderIdRoute
  '/_authenticated/admin/service-matches': typeof AuthenticatedAdminServiceMatchesRouteWithChildren
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/dashboard/account': typeof AuthenticatedDashboardAccountRoute
  '/_authenticated/dashboard/branding': typeof AuthenticatedDashboardBrandingRoute
  '/_authenticated/dashboard/clients': typeof AuthenticatedDashboardClientsRoute
  '/_authenticated/dashboard/demo': typeof AuthenticatedDashboardDemoRoute
  '/_authenticated/dashboard/marketplace': typeof AuthenticatedDashboardMarketplaceRoute
  '/_authenticated/dashboard/orders': typeof AuthenticatedDashboardOrdersRoute
  '/_authenticated/dashboard/payouts': typeof AuthenticatedDashboardPayoutsRoute
  '/_authenticated/dashboard/pricing': typeof AuthenticatedDashboardPricingRoute
  '/_authenticated/dashboard/stats': typeof AuthenticatedDashboardStatsRoute
  '/_authenticated/dashboard/upgrade': typeof AuthenticatedDashboardUpgradeRoute
  '/_authenticated/dashboard/vault': typeof AuthenticatedDashboardVaultRouteWithChildren
  '/_authenticated/dashboard/work-orders': typeof AuthenticatedDashboardWorkOrdersRoute
  '/agents/match/$matchToken': typeof AgentsMatchMatchTokenRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/marketplace/feedback/$token': typeof MarketplaceFeedbackTokenRoute
  '/p/$slug/builder': typeof PSlugBuilderRoute
  '/p/$slug/demo': typeof PSlugDemoRoute
  '/work-orders/rate/$token': typeof WorkOrdersRateTokenRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/p/$slug/': typeof PSlugIndexRoute
  '/_authenticated/admin/service-matches/$matchToken': typeof AuthenticatedAdminServiceMatchesMatchTokenRoute
  '/_authenticated/agent-dashboard/work-orders/$id': typeof AuthenticatedAgentDashboardWorkOrdersIdRoute
  '/_authenticated/dashboard/vault/templates': typeof AuthenticatedDashboardVaultTemplatesRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/_authenticated/admin/service-matches/': typeof AuthenticatedAdminServiceMatchesIndexRoute
  '/_authenticated/agent-dashboard/work-orders/': typeof AuthenticatedAgentDashboardWorkOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/forgot-password'
    | '/login'
    | '/opportunities'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/admin'
    | '/agent-dashboard'
    | '/dashboard'
    | '/api/geocode-beacon'
    | '/api/geocode-branding'
    | '/api/geocode-directory-query'
    | '/api/marketplace-feedback'
    | '/api/mp-attachment'
    | '/api/mp-image'
    | '/card/$slug'
    | '/email/unsubscribe'
    | '/invite/$token'
    | '/p/$slug'
    | '/admin/$providerId'
    | '/admin/service-matches'
    | '/admin/settings'
    | '/dashboard/account'
    | '/dashboard/branding'
    | '/dashboard/clients'
    | '/dashboard/demo'
    | '/dashboard/marketplace'
    | '/dashboard/orders'
    | '/dashboard/payouts'
    | '/dashboard/pricing'
    | '/dashboard/stats'
    | '/dashboard/upgrade'
    | '/dashboard/vault'
    | '/dashboard/work-orders'
    | '/agents/match/$matchToken'
    | '/lovable/email/suppression'
    | '/marketplace/feedback/$token'
    | '/p/$slug/builder'
    | '/p/$slug/demo'
    | '/work-orders/rate/$token'
    | '/admin/'
    | '/dashboard/'
    | '/p/$slug/'
    | '/admin/service-matches/$matchToken'
    | '/agent-dashboard/work-orders/$id'
    | '/dashboard/vault/templates'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/admin/service-matches/'
    | '/agent-dashboard/work-orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/forgot-password'
    | '/login'
    | '/opportunities'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/agent-dashboard'
    | '/api/geocode-beacon'
    | '/api/geocode-branding'
    | '/api/geocode-directory-query'
    | '/api/marketplace-feedback'
    | '/api/mp-attachment'
    | '/api/mp-image'
    | '/card/$slug'
    | '/email/unsubscribe'
    | '/invite/$token'
    | '/admin/$providerId'
    | '/admin/settings'
    | '/dashboard/account'
    | '/dashboard/branding'
    | '/dashboard/clients'
    | '/dashboard/demo'
    | '/dashboard/marketplace'
    | '/dashboard/orders'
    | '/dashboard/payouts'
    | '/dashboard/pricing'
    | '/dashboard/stats'
    | '/dashboard/upgrade'
    | '/dashboard/vault'
    | '/dashboard/work-orders'
    | '/agents/match/$matchToken'
    | '/lovable/email/suppression'
    | '/marketplace/feedback/$token'
    | '/p/$slug/builder'
    | '/p/$slug/demo'
    | '/work-orders/rate/$token'
    | '/admin'
    | '/dashboard'
    | '/p/$slug'
    | '/admin/service-matches/$matchToken'
    | '/agent-dashboard/work-orders/$id'
    | '/dashboard/vault/templates'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/admin/service-matches'
    | '/agent-dashboard/work-orders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/agents'
    | '/forgot-password'
    | '/login'
    | '/opportunities'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/_authenticated/admin'
    | '/_authenticated/agent-dashboard'
    | '/_authenticated/dashboard'
    | '/api/geocode-beacon'
    | '/api/geocode-branding'
    | '/api/geocode-directory-query'
    | '/api/marketplace-feedback'
    | '/api/mp-attachment'
    | '/api/mp-image'
    | '/card/$slug'
    | '/email/unsubscribe'
    | '/invite/$token'
    | '/p/$slug'
    | '/_authenticated/admin/$providerId'
    | '/_authenticated/admin/service-matches'
    | '/_authenticated/admin/settings'
    | '/_authenticated/dashboard/account'
    | '/_authenticated/dashboard/branding'
    | '/_authenticated/dashboard/clients'
    | '/_authenticated/dashboard/demo'
    | '/_authenticated/dashboard/marketplace'
    | '/_authenticated/dashboard/orders'
    | '/_authenticated/dashboard/payouts'
    | '/_authenticated/dashboard/pricing'
    | '/_authenticated/dashboard/stats'
    | '/_authenticated/dashboard/upgrade'
    | '/_authenticated/dashboard/vault'
    | '/_authenticated/dashboard/work-orders'
    | '/agents/match/$matchToken'
    | '/lovable/email/suppression'
    | '/marketplace/feedback/$token'
    | '/p/$slug/builder'
    | '/p/$slug/demo'
    | '/work-orders/rate/$token'
    | '/_authenticated/admin/'
    | '/_authenticated/dashboard/'
    | '/p/$slug/'
    | '/_authenticated/admin/service-matches/$matchToken'
    | '/_authenticated/agent-dashboard/work-orders/$id'
    | '/_authenticated/dashboard/vault/templates'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/_authenticated/admin/service-matches/'
    | '/_authenticated/agent-dashboard/work-orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AgentsRoute: typeof AgentsRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  ApiGeocodeBeaconRoute: typeof ApiGeocodeBeaconRoute
  ApiGeocodeBrandingRoute: typeof ApiGeocodeBrandingRoute
  ApiGeocodeDirectoryQueryRoute: typeof ApiGeocodeDirectoryQueryRoute
  ApiMarketplaceFeedbackRoute: typeof ApiMarketplaceFeedbackRoute
  ApiMpAttachmentRoute: typeof ApiMpAttachmentRoute
  ApiMpImageRoute: typeof ApiMpImageRoute
  CardSlugRoute: typeof CardSlugRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  InviteTokenRoute: typeof InviteTokenRoute
  PSlugRoute: typeof PSlugRouteWithChildren
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  MarketplaceFeedbackTokenRoute: typeof MarketplaceFeedbackTokenRoute
  WorkOrdersRateTokenRoute: typeof WorkOrdersRateTokenRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card/$slug': {
      id: '/card/$slug'
      path: '/card/$slug'
      fullPath: '/card/$slug'
      preLoaderRoute: typeof CardSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mp-image': {
      id: '/api/mp-image'
      path: '/api/mp-image'
      fullPath: '/api/mp-image'
      preLoaderRoute: typeof ApiMpImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mp-attachment': {
      id: '/api/mp-attachment'
      path: '/api/mp-attachment'
      fullPath: '/api/mp-attachment'
      preLoaderRoute: typeof ApiMpAttachmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/marketplace-feedback': {
      id: '/api/marketplace-feedback'
      path: '/api/marketplace-feedback'
      fullPath: '/api/marketplace-feedback'
      preLoaderRoute: typeof ApiMarketplaceFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/geocode-directory-query': {
      id: '/api/geocode-directory-query'
      path: '/api/geocode-directory-query'
      fullPath: '/api/geocode-directory-query'
      preLoaderRoute: typeof ApiGeocodeDirectoryQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/geocode-branding': {
      id: '/api/geocode-branding'
      path: '/api/geocode-branding'
      fullPath: '/api/geocode-branding'
      preLoaderRoute: typeof ApiGeocodeBrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/geocode-beacon': {
      id: '/api/geocode-beacon'
      path: '/api/geocode-beacon'
      fullPath: '/api/geocode-beacon'
      preLoaderRoute: typeof ApiGeocodeBeaconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agent-dashboard': {
      id: '/_authenticated/agent-dashboard'
      path: '/agent-dashboard'
      fullPath: '/agent-dashboard'
      preLoaderRoute: typeof AuthenticatedAgentDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/p/$slug/': {
      id: '/p/$slug/'
      path: '/'
      fullPath: '/p/$slug/'
      preLoaderRoute: typeof PSlugIndexRouteImport
      parentRoute: typeof PSlugRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/work-orders/rate/$token': {
      id: '/work-orders/rate/$token'
      path: '/work-orders/rate/$token'
      fullPath: '/work-orders/rate/$token'
      preLoaderRoute: typeof WorkOrdersRateTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug/demo': {
      id: '/p/$slug/demo'
      path: '/demo'
      fullPath: '/p/$slug/demo'
      preLoaderRoute: typeof PSlugDemoRouteImport
      parentRoute: typeof PSlugRoute
    }
    '/p/$slug/builder': {
      id: '/p/$slug/builder'
      path: '/builder'
      fullPath: '/p/$slug/builder'
      preLoaderRoute: typeof PSlugBuilderRouteImport
      parentRoute: typeof PSlugRoute
    }
    '/marketplace/feedback/$token': {
      id: '/marketplace/feedback/$token'
      path: '/marketplace/feedback/$token'
      fullPath: '/marketplace/feedback/$token'
      preLoaderRoute: typeof MarketplaceFeedbackTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/match/$matchToken': {
      id: '/agents/match/$matchToken'
      path: '/match/$matchToken'
      fullPath: '/agents/match/$matchToken'
      preLoaderRoute: typeof AgentsMatchMatchTokenRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/_authenticated/dashboard/work-orders': {
      id: '/_authenticated/dashboard/work-orders'
      path: '/work-orders'
      fullPath: '/dashboard/work-orders'
      preLoaderRoute: typeof AuthenticatedDashboardWorkOrdersRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/vault': {
      id: '/_authenticated/dashboard/vault'
      path: '/vault'
      fullPath: '/dashboard/vault'
      preLoaderRoute: typeof AuthenticatedDashboardVaultRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/upgrade': {
      id: '/_authenticated/dashboard/upgrade'
      path: '/upgrade'
      fullPath: '/dashboard/upgrade'
      preLoaderRoute: typeof AuthenticatedDashboardUpgradeRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/stats': {
      id: '/_authenticated/dashboard/stats'
      path: '/stats'
      fullPath: '/dashboard/stats'
      preLoaderRoute: typeof AuthenticatedDashboardStatsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/pricing': {
      id: '/_authenticated/dashboard/pricing'
      path: '/pricing'
      fullPath: '/dashboard/pricing'
      preLoaderRoute: typeof AuthenticatedDashboardPricingRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/payouts': {
      id: '/_authenticated/dashboard/payouts'
      path: '/payouts'
      fullPath: '/dashboard/payouts'
      preLoaderRoute: typeof AuthenticatedDashboardPayoutsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/orders': {
      id: '/_authenticated/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof AuthenticatedDashboardOrdersRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/marketplace': {
      id: '/_authenticated/dashboard/marketplace'
      path: '/marketplace'
      fullPath: '/dashboard/marketplace'
      preLoaderRoute: typeof AuthenticatedDashboardMarketplaceRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/demo': {
      id: '/_authenticated/dashboard/demo'
      path: '/demo'
      fullPath: '/dashboard/demo'
      preLoaderRoute: typeof AuthenticatedDashboardDemoRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/clients': {
      id: '/_authenticated/dashboard/clients'
      path: '/clients'
      fullPath: '/dashboard/clients'
      preLoaderRoute: typeof AuthenticatedDashboardClientsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/branding': {
      id: '/_authenticated/dashboard/branding'
      path: '/branding'
      fullPath: '/dashboard/branding'
      preLoaderRoute: typeof AuthenticatedDashboardBrandingRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/account': {
      id: '/_authenticated/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof AuthenticatedDashboardAccountRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/service-matches': {
      id: '/_authenticated/admin/service-matches'
      path: '/service-matches'
      fullPath: '/admin/service-matches'
      preLoaderRoute: typeof AuthenticatedAdminServiceMatchesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/$providerId': {
      id: '/_authenticated/admin/$providerId'
      path: '/$providerId'
      fullPath: '/admin/$providerId'
      preLoaderRoute: typeof AuthenticatedAdminProviderIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/agent-dashboard/work-orders/': {
      id: '/_authenticated/agent-dashboard/work-orders/'
      path: '/work-orders'
      fullPath: '/agent-dashboard/work-orders/'
      preLoaderRoute: typeof AuthenticatedAgentDashboardWorkOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedAgentDashboardRoute
    }
    '/_authenticated/admin/service-matches/': {
      id: '/_authenticated/admin/service-matches/'
      path: '/'
      fullPath: '/admin/service-matches/'
      preLoaderRoute: typeof AuthenticatedAdminServiceMatchesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminServiceMatchesRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/vault/templates': {
      id: '/_authenticated/dashboard/vault/templates'
      path: '/templates'
      fullPath: '/dashboard/vault/templates'
      preLoaderRoute: typeof AuthenticatedDashboardVaultTemplatesRouteImport
      parentRoute: typeof AuthenticatedDashboardVaultRoute
    }
    '/_authenticated/agent-dashboard/work-orders/$id': {
      id: '/_authenticated/agent-dashboard/work-orders/$id'
      path: '/work-orders/$id'
      fullPath: '/agent-dashboard/work-orders/$id'
      preLoaderRoute: typeof AuthenticatedAgentDashboardWorkOrdersIdRouteImport
      parentRoute: typeof AuthenticatedAgentDashboardRoute
    }
    '/_authenticated/admin/service-matches/$matchToken': {
      id: '/_authenticated/admin/service-matches/$matchToken'
      path: '/$matchToken'
      fullPath: '/admin/service-matches/$matchToken'
      preLoaderRoute: typeof AuthenticatedAdminServiceMatchesMatchTokenRouteImport
      parentRoute: typeof AuthenticatedAdminServiceMatchesRoute
    }
  }
}

interface AuthenticatedAdminServiceMatchesRouteChildren {
  AuthenticatedAdminServiceMatchesMatchTokenRoute: typeof AuthenticatedAdminServiceMatchesMatchTokenRoute
  AuthenticatedAdminServiceMatchesIndexRoute: typeof AuthenticatedAdminServiceMatchesIndexRoute
}

const AuthenticatedAdminServiceMatchesRouteChildren: AuthenticatedAdminServiceMatchesRouteChildren =
  {
    AuthenticatedAdminServiceMatchesMatchTokenRoute:
      AuthenticatedAdminServiceMatchesMatchTokenRoute,
    AuthenticatedAdminServiceMatchesIndexRoute:
      AuthenticatedAdminServiceMatchesIndexRoute,
  }

const AuthenticatedAdminServiceMatchesRouteWithChildren =
  AuthenticatedAdminServiceMatchesRoute._addFileChildren(
    AuthenticatedAdminServiceMatchesRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminProviderIdRoute: typeof AuthenticatedAdminProviderIdRoute
  AuthenticatedAdminServiceMatchesRoute: typeof AuthenticatedAdminServiceMatchesRouteWithChildren
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminProviderIdRoute: AuthenticatedAdminProviderIdRoute,
  AuthenticatedAdminServiceMatchesRoute:
    AuthenticatedAdminServiceMatchesRouteWithChildren,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAgentDashboardRouteChildren {
  AuthenticatedAgentDashboardWorkOrdersIdRoute: typeof AuthenticatedAgentDashboardWorkOrdersIdRoute
  AuthenticatedAgentDashboardWorkOrdersIndexRoute: typeof AuthenticatedAgentDashboardWorkOrdersIndexRoute
}

const AuthenticatedAgentDashboardRouteChildren: AuthenticatedAgentDashboardRouteChildren =
  {
    AuthenticatedAgentDashboardWorkOrdersIdRoute:
      AuthenticatedAgentDashboardWorkOrdersIdRoute,
    AuthenticatedAgentDashboardWorkOrdersIndexRoute:
      AuthenticatedAgentDashboardWorkOrdersIndexRoute,
  }

const AuthenticatedAgentDashboardRouteWithChildren =
  AuthenticatedAgentDashboardRoute._addFileChildren(
    AuthenticatedAgentDashboardRouteChildren,
  )

interface AuthenticatedDashboardVaultRouteChildren {
  AuthenticatedDashboardVaultTemplatesRoute: typeof AuthenticatedDashboardVaultTemplatesRoute
}

const AuthenticatedDashboardVaultRouteChildren: AuthenticatedDashboardVaultRouteChildren =
  {
    AuthenticatedDashboardVaultTemplatesRoute:
      AuthenticatedDashboardVaultTemplatesRoute,
  }

const AuthenticatedDashboardVaultRouteWithChildren =
  AuthenticatedDashboardVaultRoute._addFileChildren(
    AuthenticatedDashboardVaultRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAccountRoute: typeof AuthenticatedDashboardAccountRoute
  AuthenticatedDashboardBrandingRoute: typeof AuthenticatedDashboardBrandingRoute
  AuthenticatedDashboardClientsRoute: typeof AuthenticatedDashboardClientsRoute
  AuthenticatedDashboardDemoRoute: typeof AuthenticatedDashboardDemoRoute
  AuthenticatedDashboardMarketplaceRoute: typeof AuthenticatedDashboardMarketplaceRoute
  AuthenticatedDashboardOrdersRoute: typeof AuthenticatedDashboardOrdersRoute
  AuthenticatedDashboardPayoutsRoute: typeof AuthenticatedDashboardPayoutsRoute
  AuthenticatedDashboardPricingRoute: typeof AuthenticatedDashboardPricingRoute
  AuthenticatedDashboardStatsRoute: typeof AuthenticatedDashboardStatsRoute
  AuthenticatedDashboardUpgradeRoute: typeof AuthenticatedDashboardUpgradeRoute
  AuthenticatedDashboardVaultRoute: typeof AuthenticatedDashboardVaultRouteWithChildren
  AuthenticatedDashboardWorkOrdersRoute: typeof AuthenticatedDashboardWorkOrdersRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAccountRoute: AuthenticatedDashboardAccountRoute,
    AuthenticatedDashboardBrandingRoute: AuthenticatedDashboardBrandingRoute,
    AuthenticatedDashboardClientsRoute: AuthenticatedDashboardClientsRoute,
    AuthenticatedDashboardDemoRoute: AuthenticatedDashboardDemoRoute,
    AuthenticatedDashboardMarketplaceRoute:
      AuthenticatedDashboardMarketplaceRoute,
    AuthenticatedDashboardOrdersRoute: AuthenticatedDashboardOrdersRoute,
    AuthenticatedDashboardPayoutsRoute: AuthenticatedDashboardPayoutsRoute,
    AuthenticatedDashboardPricingRoute: AuthenticatedDashboardPricingRoute,
    AuthenticatedDashboardStatsRoute: AuthenticatedDashboardStatsRoute,
    AuthenticatedDashboardUpgradeRoute: AuthenticatedDashboardUpgradeRoute,
    AuthenticatedDashboardVaultRoute:
      AuthenticatedDashboardVaultRouteWithChildren,
    AuthenticatedDashboardWorkOrdersRoute:
      AuthenticatedDashboardWorkOrdersRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAgentDashboardRoute: typeof AuthenticatedAgentDashboardRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAgentDashboardRoute:
    AuthenticatedAgentDashboardRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AgentsRouteChildren {
  AgentsMatchMatchTokenRoute: typeof AgentsMatchMatchTokenRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsMatchMatchTokenRoute: AgentsMatchMatchTokenRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

interface PSlugRouteChildren {
  PSlugBuilderRoute: typeof PSlugBuilderRoute
  PSlugDemoRoute: typeof PSlugDemoRoute
  PSlugIndexRoute: typeof PSlugIndexRoute
}

const PSlugRouteChildren: PSlugRouteChildren = {
  PSlugBuilderRoute: PSlugBuilderRoute,
  PSlugDemoRoute: PSlugDemoRoute,
  PSlugIndexRoute: PSlugIndexRoute,
}

const PSlugRouteWithChildren = PSlugRoute._addFileChildren(PSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AgentsRoute: AgentsRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  ApiGeocodeBeaconRoute: ApiGeocodeBeaconRoute,
  ApiGeocodeBrandingRoute: ApiGeocodeBrandingRoute,
  ApiGeocodeDirectoryQueryRoute: ApiGeocodeDirectoryQueryRoute,
  ApiMarketplaceFeedbackRoute: ApiMarketplaceFeedbackRoute,
  ApiMpAttachmentRoute: ApiMpAttachmentRoute,
  ApiMpImageRoute: ApiMpImageRoute,
  CardSlugRoute: CardSlugRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  InviteTokenRoute: InviteTokenRoute,
  PSlugRoute: PSlugRouteWithChildren,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  MarketplaceFeedbackTokenRoute: MarketplaceFeedbackTokenRoute,
  WorkOrdersRateTokenRoute: WorkOrdersRateTokenRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
