-- ============================================================
-- INTENTIONALLY EMPTY — duplicate of earlier migrations.
-- ============================================================
--
-- This file was originally a regenerated mega-migration that
-- duplicated the schema produced by
--   * 20260418010000_production_vault_assets.sql  (vault_category,
--     vault_assets + RLS + storage bucket)
--   * 20260418020000_property_docs_engine.sql     (vault_templates,
--     property_extractions, lus_freezes, enforce_lus_freeze trigger)
--
-- None of the duplicate CREATEs use IF NOT EXISTS, so on any fresh
-- database it would error out with "relation already exists" after
-- the two earlier migrations ran. In practice that means this
-- migration was never successfully applied alongside the
-- canonical files — but its filename still lives in
-- `supabase_migrations.schema_migrations` for some historical
-- environments.
--
-- Removing the file entirely is acceptable (no environment lost
-- schema), but we keep the file as a no-op so the historical
-- `schema_migrations` entry continues to resolve cleanly and future
-- fresh installs stop trying to re-run a guaranteed-failing
-- migration. See AUDIT_REMEDIATION.md (Phase 6) for context.

SELECT 1 WHERE FALSE;
